server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

env:
  name: "prometheus-manager-master"
  version: "v0.0.1"
  namespace: "prometheus-manager"
  metadata:
    env: "dev"
    description: "Kratos Layout App"

registrar:
  etcd:
    endpoints:
      - ""

trace:
  endpoint: http://127.0.0.1:14268/api/traces

nodes:
  http:
    - addr: 127.0.0.1:9001
      timeout: 1s
    - addr: 127.0.0.1:9002
      timeout: 1s

  grpc:
    - addr: 127.0.0.1:9001
      timeout: 1s
    - addr: 127.0.0.1:9002
      timeout: 1s