server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s

data:
  database:
    driver: mysql
    source: root:6cd9aa521e1636b02dd1edd5e3ed22c8@tcp(localhost:33060)/prometheus-manager?charset=utf8mb4&parseTime=True&loc=Local
    debug: true
  redis:
    addr: localhost:6379
    password: redis#single#test
    read_timeout: 0.2s
    write_timeout: 0.2s

apiWhite:
  all:
    - /api.auth.Auth/Login
    - /api.auth.Auth/Captcha

  jwtApi:

  rbacApi:
    - /api.auth.Auth/Logout
    - /api.auth.Auth/RefreshToken

email:
  host: smtp.163.com
  port: 25
  user: aidedevops@163.com
  pass:

log:
  filename: ./log/prometheus-server.log
  level: debug
  encoder: json
  maxSize: 2
  compress: true

mq:
  kafka:
    groupId: prometheus-server
    endpoints:
      - localhost:9092
    topics:
      - alert-hook
