server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

trace:
  endpoint: http://127.0.0.1:14268/api/traces

strategy:
  load_interval: 1m
  path:
    - ""

env:
  name: "prometheus-manager-node"
  version: "v0.0.1"
  namespace: "prometheus-manager"
  metadata:
    description: "Kratos Layout App"
    env: "local"
