# 通信服务配置
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

# 链路追踪 jaeger
trace:
  endpoint: http://127.0.0.1:14268/api/traces

# 策略加载 prometheus config
strategy:
  # 加载策略的频率
  load_interval: 10s
  # 是否开启策略加载
  enable: false
  # prometheus数据源, 支持多个,
  prom_datasources:
    - name: "prometheus-node"
      type: "prometheus"
      url: "http://localhost:9090"
      access: ""
      # 默认的reload地址
      reload_path: "http://localhost:9090/-/reload"
      # 目录为绝对路径或者相对configs路径
      path:
        - "rule_temp"
        - "rule_temp/apache"
        - "rule_temp/core_dns"

# 运行环境配置
env:
  name: "prometheus-manager-node"
  version: "v0.0.1"
  namespace: "prometheus-manager"
  metadata:
    description: "Kratos Layout App"
    env: "local"

# 服务注册和发现 ETCD
registrar:
  etcd:
    endpoints:
      - localhost:20000
      - localhost:20002
      - localhost:20004

# 告警配置, 目前采用kafka
kafka:
  # 推送告警信息的topic
  alert_topic: "prometheus-manager-node-alert"
  # kafka集群地址
  endpoints:
    - "localhost:9092"
